name = "Minimalist"
license = "Apache License 2.0"
licenselink = ""
description = ""
homepage = ""
tags = ["", ""]
features = ["", ""]
min_version = 0.14

[author]
  name = "Digitalcraftsman"
  homepage = "https://github.com/digitalcraftsman"

# If porting an existing theme
[original]
  name = "Raphael Riegger"
  homepage = "http://rriegger.com/"
  repo = "https://github.com/rriegger/MinimalisticBlogTheme"
